object Form1: TForm1
  Left = 0
  Top = 0
  Caption = 'Form1'
  ClientHeight = 311
  ClientWidth = 643
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object lv1: TListView
    Left = 0
    Top = 0
    Width = 643
    Height = 311
    Align = alClient
    Columns = <>
    TabOrder = 0
    ViewStyle = vsReport
    ExplicitLeft = 40
    ExplicitTop = 72
    ExplicitWidth = 250
    ExplicitHeight = 150
  end
end
